service: aws-python-youtube-pubsub-to-discord
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true

functions:
  webhook:
    handler: handler.webhook
    environment:
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
      DISCORD_ROLE_ID: ${env:DISCORD_ROLE_ID}
    events:
      - httpApi:
          path: /webhook
          method: POST


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    useDownloadCache: true
    useStaticCache: true
